apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    {{- include "warden.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  ENCRYPTION_KEY: {{ .Values.env.ENCRYPTION_KEY | quote }}
  OIDC_ISSUER: {{ .Values.env.OIDC_ISSUER | quote }}
  OIDC_CLIENT_ID: {{ .Values.env.OIDC_CLIENT_ID | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.env.OIDC_CLIENT_SECRET | quote }}
  OIDC_REDIRECT_URL: {{ .Values.env.OIDC_REDIRECT_URL | quote }}
  SERVER_PORT: {{ .Values.env.SERVER_PORT | quote }}
  ON_CALL_PROVIDER: {{ .Values.env.ON_CALL_PROVIDER | quote }}
  ON_CALL_API_KEY: {{ .Values.env.ON_CALL_API_KEY | quote }}
