{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "warden.fullname" . }}
  labels:
    {{- include "warden.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "warden.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
{{- end }}
